/**
 * Migration: Create the `leads` table
 *
 * A "migration" is a script that changes the database structure.
 * - `up` runs when you apply the migration (creates the table)
 * - `down` runs when you roll back (drops the table)
 *
 * Knex tracks which migrations have run so they don't run twice.
 */

import type { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('leads', (table) => {
    // Primary key: UUID auto-generated by PostgreSQL
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'));

    // Tenant isolation: EVERY query must filter by this
    table.uuid('tenant_id').notNullable();

    // Who created this lead
    table.uuid('user_id').notNullable();

    // Basic lead info
    table.string('name').notNullable();
    table.string('phone').notNullable();
    table.string('country_code').notNullable();
    table.string('e164').notNullable(); // e.g. +919876543210

    // Nullable: not every lead has email
    table.string('email').nullable();

    // Which agent is responsible for this lead (nullable = unassigned)
    table.uuid('assigned_to').nullable();

    // The scheduled follow-up date (nullable = no follow-up scheduled)
    table.date('follow_up_date').nullable();

    // Timestamps: PostgreSQL TIMESTAMPTZ includes timezone info
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());

    // Indexes for fast filtering
    // We almost always filter by tenant_id, so index it
    table.index('tenant_id');
    // Role-based visibility: agents query by assigned_to
    table.index('assigned_to');
    // Free-text search needs fast name/phone lookups
    table.index('name');
  });
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('leads');
}
